chore(build): replace black,flake8 with ruff
Ruff is faster, better supported, and just better.

Remove the different line widths for spiffe-tls and address a problem
flagged by ruff:

```
F811 Redefinition of unused `wait_for_socket` from line 168
   --> src/spiffetls/util.py:145:5
    |
145 | def wait_for_socket(
    |     ^^^^^^^^^^^^^^^ `wait_for_socket` redefined here
146 |     sock: socket.socket,
147 |     read: bool = False,
    |
   ::: src/spiffetls/util.py:168:12
    |
166 |     # decision if someone goes wild with monkeypatching select.poll after
167 |     # we're imported.
168 |     global wait_for_socket
    |            --------------- previous definition of `wait_for_socket` here
169 |     if _have_working_poll():
170 |         wait_for_socket = poll_wait_for_socket
    |
help: Remove definition: `wait_for_socket`
```

Signed-off-by: Tamir Duberstein <tamird@gmail.com>